.PHONY: clean

TAG_NAME:=${TAG_NAME}
TRAVIS_TAG:=${TRAVIS_TAG}
TRAVIS_BRANCH:=${TRAVIS_BRANCH}
VERSION ?= $(if $(TRAVIS_TAG),$(TRAVIS_TAG),$(if $(TAG_NAME),$(TAG_NAME),dev))
OPENAPIGEN_VERSION ?= v3.3.4

deploy_pypi:
ifdef VERSION
	rm -rf dist

	cd api && python setup.py sdist bdist_wheel

	twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} api/dist/*
else
	@echo "not tagged"
endif

init:
	pip install pipenv
	pipenv install --dev

test:
	pipenv run py.test tests

clean:
	rm -rf api
	rm swagger.yaml

2to3:
	docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local openapitools/openapi-generator-cli:${OPENAPIGEN_VERSION} \
	           generate -i /local/swagger.json \
	           -g openapi-yaml -o /local/openapi-yaml
	cp openapi-yaml/openapi/openapi.yaml swagger.yaml
	rm -rf openapi-yaml

patch:
	pipenv run python patch_yaml.py

api: swagger.yaml Makefile
	docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local openapitools/openapi-generator-cli:${OPENAPIGEN_VERSION} \
	           generate -i /local/swagger.yaml \
	           --git-user-id rienafairefr \
	           --git-repo-id pybudgea \
	           -g python -o /local/api -DprojectName=pybudgea -DpackageName=budgea \
	           -DpackageVersion="$(VERSION)" -DappDescription="This is pybudgea, an autogenerated package to access Budget Insight API"\
	           -DappName="pybudgea" -DinfoEmail="rienafairefr@gmail.com"
